#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

cleanCase

#Remove file
rm -f log.* > /dev/null 2>&1
rm -f *.o*
rm -rf processor*

#------------------------------------------------------------------------------

