#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

foamCleanPolyMesh
cleanCase0

# Remove surface and features
rm -f constant/triSurface/airplane.eMesh
rm -rf constant/extendedFeatureEdgeMesh
rm -rf processor*
rm -f Allrun_PJ.*

#------------------------------------------------------------------------------
