#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh

runApplication surfaceFeatureExtract

runApplication decomposePar

runParallel snappyHexMesh -overwrite

restore0Dir -processor

runParallel $(getApplication)

runApplication reconstructParMesh -constant
runApplication reconstructPar -latestTime

exit

#------------------------------------------------------------------------------
